### ISSUE TITLE
Deezer page stops refreshing/displaying content after a song is played

### ISSUE THREAD

**Issue by MateuszKubuszok** [tiliado/nuvola-app-deezer#5] opened 2016-04-01 12:46 UTC
Once I start playing any song window seems to stop refreshing its content - I can see that the cursor changes when I hover over something that should be clickable page element (control buttons), but no visual change is noticable. Scrolling also stops working. However besides that everything works fine - when I guess where some control element is placed I can still use it, gnome integration also allows me to pause/resume/skip songs. After I resize window or go into another workspace and move back content is replaced with something like that:

![screenshot from 2016-04-01 14 34 09](https://cloud.githubusercontent.com/assets/1900121/14206919/dbfe5624-f816-11e5-9769-6504dfc326cb.png)

To be able to get functional page again I have to use home or refresh button. Basically whole issue gaves impression that page stops repainting content once any song is played.

I have installed Debian 8 (jessie) 64-bit with Gnome 3.1.4.1 and Nuvola Player 3 Version 5.0.

Is there something I could do to help figuring out the issue?

**Comment by MatthiasBendel** [comment] 2016-04-04 08:29
Hey, I have this problem, too. I'm running Nuvola Player 3.0.1 and Deezer 2.3 on Ubuntu 14.04.
Please let me know if I can do anything! Thanks!

**Comment by fenryxo** [comment] 2016-04-06 20:14
Hello. Thanks for taking the time to report this issue. Unfortunately, I'm not able to reproduce it on my system (Debian 8 Jessie). Does the issue happen always or only occasionally? Does it also happen in WebKitGtk MiniBrowser (see bellow)?

*  `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser` (64bit system)
* `/usr/lib/i386-linux-gnu/webkit2gtk-4.0/MiniBrowser` (32bit system)

**Comment by MateuszKubuszok** [comment] 2016-04-07 10:33
Thanks for reply!

After testing the Deezer with `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser` I've got 
![screenshot from 2016-04-07 12 13 28](https://cloud.githubusercontent.com/assets/1900121/14348044/52b17bdc-fcba-11e5-8bd3-de87e8a2cc73.png)
several seconds into the song. Then on each page refresh issue persisted. On first restart the same. However, after another restart it stabilized.

When I tried that with nuvola-app after some restarting it started working again. I usually have the apps opened for several days - maybe some memory leak in either Deezer or MiniBrowser causes renderer crash? I'll look at memory usage next time it happens.

**Comment by fenryxo** [comment] 2016-04-14 10:42
Thanks for your feedback. The occurrence of the issue in MiniBrowser suggests it may be a quirk in WebKitGTK library rather than in Nuvola Player. I might look at the WebKitGTK bugzilla to find some related bug reports.

**Comment by fenryxo** [comment] 2016-05-20 11:28
Hello. Does the issue still persist?

**Comment by MateuszKubuszok** [comment] 2016-05-21 19:07
It does. A temporary workaround is to restart application (refreshing, won't solve the issue once it start happening). One have to wait quite a while before it occurs, but it eventually happens.

**Comment by fenryxo** [comment] 2016-05-21 19:41
Does the issue occur also with `libwebkit2gtk-4.0-37` 2.12.0-2~bpo8+1 from jessie-backports?

**Comment by fenryxo** [comment] 2016-07-22 14:55
Hello. I'm closing this issue as I haven't received any response to my request for more information I posted on May 21st, 2016. If the issue still persists, feel free to add missing information and reopen this ticket.

**Closed by fenryxo** 2016-07-22 14:55 UTC
Labels: bug
