### ISSUE TITLE
Dezzer have a new web app!

### ISSUE THREAD

**Issue by pedroSBastos** [tiliado/nuvola-app-deezer#17] opened 2018-09-28 09:24 UTC
Nuvola app dosen't support the new Deezer web app. Notifications, Next Song, Previous Song etc... dosen't work.

**Comment by fenryxo** [comment] 2018-09-28 09:57
Hello @pedroSBastos. This should be fixed in Deezer script 3.0.15. Run `flatpak update --system; flatpak update --user` to make sure all your Nuvola packages are up-to-date.

**Closed by fenryxo** 2018-09-28 09:57 UTC
Labels: status: duplicate

**Comment by fenryxo** [comment] 2018-09-28 10:05
If the issue is reproducible with the latest Nuvola, report the issue here: https://github.com/tiliado/nuvolaruntime/issues/new/choose
